### ISSUE TITLE
Which config for the pretrained model?

### ISSUE THREAD

**Issue by karolmajek** [hasanirtiza/PedesFormer#2]
Which config should I use for the pretrained model?

**Comment by hasanirtiza** [comment]
[Try this](https://github.com/hasanirtiza/PedesFormer-Transformer-Networks-For-Pedestrian-Detection/blob/main/configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py).
