### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by 377fsq** [hasanirtiza/PedesFormer#3]
Is the environment configuration consistent with pedestron?

**Comment by hasanirtiza** [comment]
No, its not. You can find instruction about installation [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md).

**Comment by 377fsq** [comment]
Thank you!Can you provide your mmcv-full,pytorch and cuda version?I want to install a consistent environment for training.

**Comment by hasanirtiza** [comment]
If you install the version specified in the official repo, regardless of the versions etc., it should be consistent. Only caveat is, have a look the official [Swin repo](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection), they mention about `Apex (optional)`, this might slightly alter the results.

**Comment by 377fsq** [comment]
Got it.Thank you so much!
