### ISSUE TITLE
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by ajay1234567899** [hasanirtiza/PedesFormer#5]
Hello sir,

I was trying to run your program on google colab and my local system.
I did follow the instructions that were mentioned in your link.

mmdetections was successfully installed.
I downloaded the config file and the pre-trained weights into the directory and ran the following command.
python ./demo/image_demo.py ./demo/demo.png ./pedformer_config.py ./epoch_9.pth 

And now I get the following error.

![image](https://user-images.githubusercontent.com/33980693/183299591-77cddff9-c194-49be-8fa1-45290fcc0baa.png)

Please do let me know what has to be done.
I am new to mmdetections.

waiting for your replay
thank you

**Comment by hasanirtiza** [comment]
[This](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/188) should help.
