### ISSUE TITLE
Experiment results and model links for swin-tiny/small?

### ISSUE THREAD

**Issue by CMSC740Student** [hasanirtiza/PedesFormer#9]
Dear Author, 

Are there any experiment results with swin-tiny and small variants?
If yes, where can I find the experimental results and model links?

Thank you!

**Comment by hasanirtiza** [comment]
Unfortunately, I do not have the log anywhere, whatever we have, it is reported in the paper(Arxiv version). We did do some experiments with pvt-v2, which was worse than swin.
